### ISSUE TITLE
Reader conditional is recognizing :clj

### ISSUE THREAD

**Issue by mfikes** [mfikes/himera#1]
```clojure
#?(:bad 1 :clj 2 :cljs 3)
```
evaluates to `2`

**Comment by bensu** [comment]
According to the [Reader Conditionals Proposal](http://dev.clojure.org/display/design/Reader+Conditionals):

> The platform feature (:clj) will always be present.

**Comment by mfikes** [comment]
@bensu That's cool. Hrm. The ClojureScript REPL doesn't behave that way:

```
$ rlwrap java -jar cljs.jar -m cljs.repl.node
ClojureScript Node.js REPL server listening on 49362
To quit, type: :cljs/quit
cljs.user=> #?(:bad 1 :clj 2 :cljs 3)
3
cljs.user=> #?(:bad 1 :clj 2 :x 3)
:hello
:hello
```
